version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-tax
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  mysql:
    image: mysql:5.7.22
    container_name: mysql-tax
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tax_service_db
