DROP TABLE IF EXISTS taxes;

CREATE TABLE IF NOT EXISTS taxes(
  id VARCHAR (32) PRIMARY KEY,
  value DECIMAL (14, 6) NOT NULL,
  created_at DATETIME NOT NULL
);

INSERT INTO taxes values ('ICMS', 0.17, CURRENT_TIMESTAMP());
INSERT INTO taxes values ('ISS', 0.07, CURRENT_TIMESTAMP());
INSERT INTO taxes values ('ITBI', 0.04, CURRENT_TIMESTAMP());
INSERT INTO taxes values ('PIS', 0.01, CURRENT_TIMESTAMP());
INSERT INTO taxes values ('COFINS', 0.01, CURRENT_TIMESTAMP());
